In [ ]:
import pandas as pd
f = pd.read_csv(r"Books.csv")

In [3]:
import pandas as pd
# f = pd.read_csv(r"Books.csv")
df = pd.read_csv(r"Books.csv", dtype={'Year-Of-Publication': str})
print("jo")
df

jo

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [6]:
group_frame = df.groupby('Year-Of-Publication')

In [15]:
group_frame.max(numeric_only=True)
# group_frame.mean(numeric_only=True)

Empty DataFrame
Columns: []
Index: [0, 1376, 1378, 1806, 1897, 1900, 1901, 1902, 1904, 1906, 1908, 1909, 1910, 1911, 1914, 1917, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, ...]

[118 rows x 0 columns]

In [11]:
# Count how many books are in each year
year_counts = df['Year-Of-Publication'].value_counts()

# Display the results
year_counts.head(50) # Shows the top 20 years with the most books

Year-Of-Publication
2002    17627
1999    17431
2001    17359
2000    17232
1998    15766
1997    14890
2003    14358
1996    14030
1995    13546
1994    11796
1993    10602
1992     9906
1991     9389
1990     8660
1989     7936
1988     7492
1987     6529
1986     5841
2004     5839
1985     5343
1984     4986
0        4618
1983     4499
1982     4197
1981     3279
1980     2676
1979     2208
1978     2131
1977     1897
1976     1597
1975     1219
1974     1023
1973      923
1972      772
1971      540
1970      459
1969      339
1968      233
1966      183
1967      176
1965      173
1964      149
1960      133
1961      132
1963      132
1962      123
1959      103
1958       77
1957       76
1956       74
Name: count, dtype: int64

In [19]:
df.groupby(['Year-Of-Publication', 'Book-Author']).agg({'Year-Of-Publication': 'count'})

                                        Year-Of-Publication
Year-Of-Publication Book-Author
0                   A A Milne                             5
                    A B Guthrie                           2
                    A Bodenburg Sommer                    1
                    A E Hartink                           2
                    A E Van Vogt                          2
...                                                     ...
2038                Eugene O'Neill                        1
2050                Lewis Carroll                         1
                    Nikolaus Pevsner                      1
DK Publishing Inc   2000                                  2
Gallimard           2003                                  1

[202041 rows x 1 columns]