In [1]:
import pandas as pd
print("version: 1.0.1")

version: 1.0.1

In [2]:
import kagglehub

path = kagglehub.dataset_download("saurabhbagchi/books-dataset")

print("Path to dataset files:", path)

c:\Users\Shaked\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\Shaked\.cache\kagglehub\datasets\saurabhbagchi\books-dataset\versions\1

In [ ]:
import pandas as pd

ratings = pd.read_csv(
    path + r"\books_data\Ratings.csv",
    encoding="latin-1",
    sep=";",
    engine="python",
    on_bad_lines="warn"
)

books = pd.read_csv(
    path + r"\books_data\Books.csv",
    encoding="latin-1",
    sep=";",
    engine="python",
    on_bad_lines="warn"
)

user = pd.read_csv(
    path + r"\books_data\Users.csv",
    encoding="latin-1",
    sep=";",
    engine="python",
    on_bad_lines="warn"
)

Skipping line 21689: ';' expected after '"'
Skipping line 45329: ';' expected after '"'
Skipping line 45330: ';' expected after '"'
Skipping line 183262: ';' expected after '"'
Skipping line 210093: ';' expected after '"'
Skipping line 531938: ';' expected after '"'
Skipping line 663237: ';' expected after '"'
Skipping line 824822: ';' expected after '"'
Skipping line 877349: ';' expected after '"'
Skipping line 941679: ';' expected after '"'
Skipping line 1134132: ';' expected after '"'
Skipping line 1145176: ';' expected after '"'
Skipping line 1145177: ';' expected after '"'
Skipping line 1148551: ';' expected after '"'
Skipping line 815: ';' expected after '"'
Skipping line 1679: ';' expected after '"'
Skipping line 2531: ';' expected after '"'
Skipping line 2640: ';' expected after '"'
Skipping line 3236: ';' expected after '"'
Skipping line 3256: ';' expected after '"'
Skipping line 4906: ';' expected after '"'
Skipping line 6452: ';' expected after '"'
Skipping line 8349: ';' expected after '"'
Skipping line 9669: ';' expected after '"'
Skipping line 9723: ';' expected after '"'
Skipping line 10010: ';' expected after '"'
Skipping line 10192: ';' expected after '"'
Skipping line 10754: ';' expected after '"'
Skipping line 10824: ';' expected after '"'
Skipping line 10862: ';' expected after '"'
Skipping line 11442: ';' expected after '"'
Skipping line 11584: ';' expected after '"'
Skipping line 11859: ';' expected after '"'
Skipping line 12206: ';' expected after '"'
Skipping line 12229: ';' expected after '"'
Skipping line 12719: ';' expected after '"'
Skipping line 12885: ';' expected after '"'
Skipping line 13376: ';' expected after '"'
Skipping line 13380: ';' expected after '"'
Skipping line 13394: ';' expected after '"'
Skipping line 13639: ';' expected after '"'
Skipping line 14346: ';' expected after '"'
Skipping line 14723: ';' expected after '"'
Skipping line 14769: ';' expected after '"'
Skipping line 14936: ';' expected after '"'
Skipping line 14977: ';' expected after '"'
Skipping line 15633: ';' expected after '"'
Skipping line 15690: ';' expected after '"'
Skipping line 15772: ';' expected after '"'
Skipping line 15853: ';' expected after '"'
Skipping line 16088: ';' expected after '"'
Skipping line 16090: ';' expected after '"'
Skipping line 17320: ';' expected after '"'
Skipping line 17410: ';' expected after '"'
Skipping line 17665: ';' expected after '"'
Skipping line 17997: ';' expected after '"'
Skipping line 18095: ';' expected after '"'
Skipping line 18839: ';' expected after '"'
Skipping line 19156: ';' expected after '"'
Skipping line 19510: ';' expected after '"'
Skipping line 20266: ';' expected after '"'
Skipping line 20434: ';' expected after '"'
Skipping line 21438: ';' expected after '"'
Skipping line 21602: ';' expected after '"'
Skipping line 21719: ';' expected after '"'
Skipping line 21889: ';' expected after '"'
Skipping line 22197: ';' expected after '"'
Skipping line 22460: ';' expected after '"'
Skipping line 23571: ';' expected after '"'
Skipping line 23786: ';' expected after '"'
Skipping line 24257: ';' expected after '"'
Skipping line 24719: ';' expected after '"'
Skipping line 24924: ';' expected after '"'
Skipping line 25849: ';' expected after '"'
Skipping line 26079: ';' expected after '"'
Skipping line 26151: ';' expected after '"'
Skipping line 26234: ';' expected after '"'
Skipping line 26235: ';' expected after '"'
Skipping line 26299: ';' expected after '"'
Skipping line 26538: ';' expected after '"'
Skipping line 26659: ';' expected after '"'
Skipping line 26660: ';' expected after '"'
Skipping line 27295: ';' expected after '"'
Skipping line 27758: ';' expected after '"'
Skipping line 27759: ';' expected after '"'
Skipping line 27781: ';' expected after '"'
Skipping line 28220: ';' expected after '"'
Skipping line 28297: ';' expected after '"'
Skipping line 28443: ';' expected after '"'
Skipping line 28600: ';' expected after '"'
Skipping line 28803: ';' expected after '"'
Skipping line 28913: ';' expected after '"'
Skipping line 29505: ';' expected after '"'
Skipping line 29938: ';' expected after '"'
Skipping line 30821: ';' expected after '"'
Skipping line 31366: ';' expected after '"'
Skipping line 32075: ';' expected after '"'
Skipping line 33098: ';' expected after '"'
Skipping line 33658: ';' expected after '"'
Skipping line 34203: ';' expected after '"'
Skipping line 34252: ';' expected after '"'
Skipping line 34705: ';' expected after '"'
Skipping line 34827: ';' expected after '"'
Skipping line 35901: ';' expected after '"'
Skipping line 35902: ';' expected after '"'
Skipping line 36035: ';' expected after '"'
Skipping line 36394: ';' expected after '"'
Skipping line 37131: ';' expected after '"'
Skipping line 40079: ';' expected after '"'
Skipping line 40441: ';' expected after '"'
Skipping line 41193: ';' expected after '"'
Skipping line 42360: ';' expected after '"'
Skipping line 42524: ';' expected after '"'
Skipping line 42607: ';' expected after '"'
Skipping line 42627: ';' expected after '"'
Skipping line 42628: ';' expected after '"'
Skipping line 42699: ';' expected after '"'
Skipping line 42743: ';' expected after '"'
Skipping line 42755: ';' expected after '"'
Skipping line 42795: ';' expected after '"'
Skipping line 42816: ';' expected after '"'
Skipping line 42952: ';' expected after '"'
Skipping line 43134: ';' expected after '"'
Skipping line 43667: ';' expected after '"'
Skipping line 44917: ';' expected after '"'
Skipping line 45713: ';' expected after '"'
Skipping line 46741: ';' expected after '"'
Skipping line 47598: ';' expected after '"'
Skipping line 48121: ';' expected after '"'
Skipping line 48132: ';' expected after '"'
Skipping line 48547: ';' expected after '"'
Skipping line 49526: ';' expected after '"'
Skipping line 50265: ';' expected after '"'
Skipping line 50272: ';' expected after '"'
Skipping line 50413: ';' expected after '"'
Skipping line 51060: ';' expected after '"'
Skipping line 51227: ';' expected after '"'
Skipping line 51256: ';' expected after '"'
Skipping line 51685: ';' expected after '"'
Skipping line 51751: ';' expected after '"'
Skipping line 52174: ';' expected after '"'
Skipping line 54725: ';' expected after '"'
Skipping line 55120: ';' expected after '"'
Skipping line 55194: ';' expected after '"'
Skipping line 55312: ';' expected after '"'
Skipping line 55483: ';' expected after '"'
Skipping line 55740: ';' expected after '"'
Skipping line 56523: ';' expected after '"'
Skipping line 56528: ';' expected after '"'
Skipping line 56827: ';' expected after '"'
Skipping line 56901: ';' expected after '"'
Skipping line 57373: ';' expected after '"'
Skipping line 57377: ';' expected after '"'
Skipping line 57943: ';' expected after '"'
Skipping line 58309: ';' expected after '"'
Skipping line 58386: ';' expected after '"'
Skipping line 58578: ';' expected after '"'
Skipping line 58600: ';' expected after '"'
Skipping line 58969: ';' expected after '"'
Skipping line 59060: ';' expected after '"'
Skipping line 59234: ';' expected after '"'
Skipping line 59494: ';' expected after '"'
Skipping line 59507: ';' expected after '"'
Skipping line 59612: ';' expected after '"'
Skipping line 59803: ';' expected after '"'
Skipping line 59988: ';' expected after '"'
Skipping line 60739: ';' expected after '"'
Skipping line 60744: ';' expected after '"'
Skipping line 61818: ';' expected after '"'
Skipping line 61821: ';' expected after '"'
Skipping line 62200: ';' expected after '"'
Skipping line 62265: ';' expected after '"'
Skipping line 62581: ';' expected after '"'
Skipping line 62777: ';' expected after '"'
Skipping line 62890: ';' expected after '"'
Skipping line 63839: ';' expected after '"'
Skipping line 64033: ';' expected after '"'
Skipping line 64253: ';' expected after '"'
Skipping line 65345: ';' expected after '"'
Skipping line 65756: ';' expected after '"'
Skipping line 66394: ';' expected after '"'
Skipping line 66446: ';' expected after '"'
Skipping line 66521: ';' expected after '"'
Skipping line 67104: ';' expected after '"'
Skipping line 67729: ';' expected after '"'
Skipping line 67924: ';' expected after '"'
Skipping line 67973: ';' expected after '"'
Skipping line 68107: ';' expected after '"'
Skipping line 68111: ';' expected after '"'
Skipping line 68134: ';' expected after '"'
Skipping line 69712: ';' expected after '"'
Skipping line 69920: ';' expected after '"'
Skipping line 70649: ';' expected after '"'
Skipping line 70764: ';' expected after '"'
Skipping line 70826: ';' expected after '"'
Skipping line 71125: ';' expected after '"'
Skipping line 71531: ';' expected after '"'
Skipping line 71615: ';' expected after '"'
Skipping line 71769: ';' expected after '"'
Skipping line 72335: ';' expected after '"'
Skipping line 72372: ';' expected after '"'
Skipping line 72572: ';' expected after '"'
Skipping line 72929: ';' expected after '"'
Skipping line 72930: ';' expected after '"'
Skipping line 72931: ';' expected after '"'
Skipping line 73156: ';' expected after '"'
Skipping line 73162: ';' expected after '"'
Skipping line 73199: ';' expected after '"'
Skipping line 73270: ';' expected after '"'
Skipping line 73849: ';' expected after '"'
Skipping line 73880: ';' expected after '"'
Skipping line 74291: ';' expected after '"'
Skipping line 75043: ';' expected after '"'
Skipping line 75071: ';' expected after '"'
Skipping line 76445: ';' expected after '"'
Skipping line 76492: ';' expected after '"'
Skipping line 76844: ';' expected after '"'
Skipping line 77231: ';' expected after '"'
Skipping line 77336: ';' expected after '"'
Skipping line 77781: ';' expected after '"'
Skipping line 77835: ';' expected after '"'
Skipping line 78089: ';' expected after '"'
Skipping line 78186: ';' expected after '"'
Skipping line 78524: ';' expected after '"'
Skipping line 78752: ';' expected after '"'
Skipping line 79118: ';' expected after '"'
Skipping line 79320: ';' expected after '"'
Skipping line 79725: ';' expected after '"'
Skipping line 79909: ';' expected after '"'
Skipping line 79974: ';' expected after '"'
Skipping line 81924: ';' expected after '"'
Skipping line 83588: ';' expected after '"'
Skipping line 83609: ';' expected after '"'
Skipping line 83907: ';' expected after '"'
Skipping line 84489: ';' expected after '"'
Skipping line 84513: ';' expected after '"'
Skipping line 84564: ';' expected after '"'
Skipping line 85035: ';' expected after '"'
Skipping line 85094: ';' expected after '"'
Skipping line 85510: ';' expected after '"'
Skipping line 86373: ';' expected after '"'
Skipping line 86429: ';' expected after '"'
Skipping line 86637: ';' expected after '"'
Skipping line 86694: ';' expected after '"'
Skipping line 86822: ';' expected after '"'
Skipping line 87322: ';' expected after '"'
Skipping line 87757: ';' expected after '"'
Skipping line 87950: ';' expected after '"'
Skipping line 88000: ';' expected after '"'
Skipping line 88405: ';' expected after '"'
Skipping line 88698: ';' expected after '"'
Skipping line 88809: ';' expected after '"'
Skipping line 88980: ';' expected after '"'
Skipping line 89309: ';' expected after '"'
Skipping line 89988: ';' expected after '"'
Skipping line 90052: ';' expected after '"'
Skipping line 90062: ';' expected after '"'
Skipping line 90210: ';' expected after '"'
Skipping line 91033: ';' expected after '"'
Skipping line 91338: ';' expected after '"'
Skipping line 91603: ';' expected after '"'
Skipping line 91658: ';' expected after '"'
Skipping line 91950: ';' expected after '"'
Skipping line 92038: ';' expected after '"'
Skipping line 92099: ';' expected after '"'
Skipping line 92232: ';' expected after '"'
Skipping line 92436: ';' expected after '"'
Skipping line 92829: ';' expected after '"'
Skipping line 92856: ';' expected after '"'
Skipping line 92948: ';' expected after '"'
Skipping line 93118: ';' expected after '"'
Skipping line 93289: ';' expected after '"'
Skipping line 93299: ';' expected after '"'
Skipping line 93760: ';' expected after '"'
Skipping line 93862: ';' expected after '"'
Skipping line 94130: ';' expected after '"'
Skipping line 94236: ';' expected after '"'
Skipping line 94316: ';' expected after '"'
Skipping line 94735: ';' expected after '"'
Skipping line 95058: ';' expected after '"'
Skipping line 95075: ';' expected after '"'
Skipping line 95244: ';' expected after '"'
Skipping line 95248: ';' expected after '"'
Skipping line 95342: ';' expected after '"'
Skipping line 95455: ';' expected after '"'
Skipping line 95482: ';' expected after '"'
Skipping line 95768: ';' expected after '"'
Skipping line 96577: ';' expected after '"'
Skipping line 96795: ';' expected after '"'
Skipping line 96899: ';' expected after '"'
Skipping line 97100: ';' expected after '"'
Skipping line 97300: ';' expected after '"'
Skipping line 98038: ';' expected after '"'
Skipping line 98119: ';' expected after '"'
Skipping line 98290: ';' expected after '"'
Skipping line 98344: ';' expected after '"'
Skipping line 98515: ';' expected after '"'
Skipping line 99472: ';' expected after '"'
Skipping line 100783: ';' expected after '"'
Skipping line 100797: ';' expected after '"'
Skipping line 101070: ';' expected after '"'
Skipping line 101472: ';' expected after '"'
Skipping line 101915: ';' expected after '"'
Skipping line 102249: ';' expected after '"'
Skipping line 102341: ';' expected after '"'
Skipping line 102440: ';' expected after '"'
Skipping line 103013: ';' expected after '"'
Skipping line 103090: ';' expected after '"'
Skipping line 103103: ';' expected after '"'
Skipping line 103653: ';' expected after '"'
Skipping line 103684: ';' expected after '"'
Skipping line 104047: ';' expected after '"'
Skipping line 104082: ';' expected after '"'
Skipping line 104319: ';' expected after '"'
Skipping line 104771: ';' expected after '"'
Skipping line 105170: ';' expected after '"'
Skipping line 105209: ';' expected after '"'
Skipping line 105342: ';' expected after '"'
Skipping line 105641: ';' expected after '"'
Skipping line 105770: ';' expected after '"'
Skipping line 105836: ';' expected after '"'
Skipping line 105893: ';' expected after '"'
Skipping line 106183: ';' expected after '"'
Skipping line 106320: ';' expected after '"'
Skipping line 106949: ';' expected after '"'
Skipping line 106976: ';' expected after '"'
Skipping line 107052: ';' expected after '"'
Skipping line 107299: ';' expected after '"'
Skipping line 107331: ';' expected after '"'
Skipping line 107357: ';' expected after '"'
Skipping line 107511: ';' expected after '"'
Skipping line 107551: ';' expected after '"'
Skipping line 107634: ';' expected after '"'
Skipping line 107763: ';' expected after '"'
Skipping line 107822: ';' expected after '"'
Skipping line 108142: ';' expected after '"'
Skipping line 108289: ';' expected after '"'
Skipping line 108529: ';' expected after '"'
Skipping line 108567: ';' expected after '"'
Skipping line 108900: ';' expected after '"'
Skipping line 109021: ';' expected after '"'
Skipping line 109643: ';' expected after '"'
Skipping line 109944: ';' expected after '"'
Skipping line 110041: ';' expected after '"'
Skipping line 110048: ';' expected after '"'
Skipping line 110548: ';' expected after '"'
Skipping line 110752: ';' expected after '"'
Skipping line 111038: ';' expected after '"'
Skipping line 111040: ';' expected after '"'
Skipping line 111174: ';' expected after '"'
Skipping line 111222: ';' expected after '"'
Skipping line 111543: ';' expected after '"'
Skipping line 111851: ';' expected after '"'
Skipping line 111852: ';' expected after '"'
Skipping line 111878: ';' expected after '"'
Skipping line 111954: ';' expected after '"'
Skipping line 111990: ';' expected after '"'
Skipping line 112119: ';' expected after '"'
Skipping line 112121: ';' expected after '"'
Skipping line 112282: ';' expected after '"'
Skipping line 112965: ';' expected after '"'
Skipping line 113461: ';' expected after '"'
Skipping line 113731: ';' expected after '"'
Skipping line 114070: ';' expected after '"'
Skipping line 114783: ';' expected after '"'
Skipping line 114934: ';' expected after '"'
Skipping line 115215: ';' expected after '"'
Skipping line 115493: ';' expected after '"'
Skipping line 115508: ';' expected after '"'
Skipping line 115751: ';' expected after '"'
Skipping line 116002: ';' expected after '"'
Skipping line 116049: ';' expected after '"'
Skipping line 116144: ';' expected after '"'
Skipping line 116171: ';' expected after '"'
Skipping line 116179: ';' expected after '"'
Skipping line 116463: ';' expected after '"'
Skipping line 117147: ';' expected after '"'
Skipping line 117176: ';' expected after '"'
Skipping line 117368: ';' expected after '"'
Skipping line 117997: ';' expected after '"'
Skipping line 118007: ';' expected after '"'
Skipping line 118225: ';' expected after '"'
Skipping line 118272: ';' expected after '"'
Skipping line 118288: ';' expected after '"'
Skipping line 119009: ';' expected after '"'
Skipping line 119535: ';' expected after '"'
Skipping line 119548: ';' expected after '"'
Skipping line 119910: ';' expected after '"'
Skipping line 120219: ';' expected after '"'
Skipping line 121400: ';' expected after '"'
Skipping line 121421: ';' expected after '"'
Skipping line 121422: ';' expected after '"'
Skipping line 121480: ';' expected after '"'
Skipping line 121768: ';' expected after '"'
Skipping line 122100: ';' expected after '"'
Skipping line 122608: ';' expected after '"'
Skipping line 123031: ';' expected after '"'
Skipping line 123127: ';' expected after '"'
Skipping line 123490: ';' expected after '"'
Skipping line 123756: ';' expected after '"'
Skipping line 123931: ';' expected after '"'
Skipping line 124311: ';' expected after '"'
Skipping line 124946: ';' expected after '"'
Skipping line 125104: ';' expected after '"'
Skipping line 125505: ';' expected after '"'
Skipping line 126333: ';' expected after '"'
Skipping line 126756: ';' expected after '"'
Skipping line 127265: ';' expected after '"'
Skipping line 127745: ';' expected after '"'
Skipping line 128018: ';' expected after '"'
Skipping line 128631: ';' expected after '"'
Skipping line 128633: ';' expected after '"'
Skipping line 128635: ';' expected after '"'
Skipping line 129190: ';' expected after '"'
Skipping line 129668: ';' expected after '"'
Skipping line 129942: ';' expected after '"'
Skipping line 130220: ';' expected after '"'
Skipping line 130307: ';' expected after '"'
Skipping line 130448: ';' expected after '"'
Skipping line 130794: ';' expected after '"'
Skipping line 131400: ';' expected after '"'
Skipping line 131541: ';' expected after '"'
Skipping line 131571: ';' expected after '"'
Skipping line 131589: ';' expected after '"'
Skipping line 131591: ';' expected after '"'
Skipping line 131662: ';' expected after '"'
Skipping line 131999: ';' expected after '"'
Skipping line 132090: ';' expected after '"'
Skipping line 132362: ';' expected after '"'
Skipping line 132516: ';' expected after '"'
Skipping line 132970: ';' expected after '"'
Skipping line 133250: ';' expected after '"'
Skipping line 133252: ';' expected after '"'
Skipping line 133254: ';' expected after '"'
Skipping line 133362: ';' expected after '"'
Skipping line 133480: ';' expected after '"'
Skipping line 133523: ';' expected after '"'
Skipping line 133625: ';' expected after '"'
Skipping line 133996: ';' expected after '"'
Skipping line 133998: ';' expected after '"'
Skipping line 134001: ';' expected after '"'
Skipping line 134004: ';' expected after '"'
Skipping line 134006: ';' expected after '"'
Skipping line 134007: ';' expected after '"'
Skipping line 135052: ';' expected after '"'
Skipping line 135121: ';' expected after '"'
Skipping line 136649: ';' expected after '"'
Skipping line 136776: ';' expected after '"'
Skipping line 137577: ';' expected after '"'
Skipping line 137613: ';' expected after '"'
Skipping line 137936: ';' expected after '"'

In [12]:
print("head of ratings dataset:")
print(ratings.head())
print("head of books dataset:")
print(books.head())
print("head of user dataset:")
print(user.head())

head of ratings dataset:
   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6
head of books dataset:
         ISBN                                         Book-Title  \
0  0195153448                                Classical Mythology
1  0002005018                                       Clara Callan
2  0060973129                               Decision in Normandy
3  0374157065  Flu: The Story of the Great Influenza Pandemic...
4  0393045218                             The Mummies of Urumchi

            Book-Author  Year-Of-Publication                   Publisher  \
0    Mark P. O. Morford                 2002     Oxford University Press
1  Richard Bruce Wright                 2001       HarperFlamingo Canada
2          Carlo D'Este                 1991             HarperPerennial
3      Gina Bari Kolata                 1999        Farrar Straus Giroux
4       E. J. W. Barber                 1999  W. W. Norton &amp; Company

                                         Image-URL-S  \
0  http://images.amazon.com/images/P/0195153448.0...
1  http://images.amazon.com/images/P/0002005018.0...
2  http://images.amazon.com/images/P/0060973129.0...
3  http://images.amazon.com/images/P/0374157065.0...
4  http://images.amazon.com/images/P/0393045218.0...

                                         Image-URL-M  \
0  http://images.amazon.com/images/P/0195153448.0...
1  http://images.amazon.com/images/P/0002005018.0...
2  http://images.amazon.com/images/P/0060973129.0...
3  http://images.amazon.com/images/P/0374157065.0...
4  http://images.amazon.com/images/P/0393045218.0...

                                         Image-URL-L
0  http://images.amazon.com/images/P/0195153448.0...
1  http://images.amazon.com/images/P/0002005018.0...
2  http://images.amazon.com/images/P/0060973129.0...
3  http://images.amazon.com/images/P/0374157065.0...
4  http://images.amazon.com/images/P/0393045218.0...
head of user dataset:
   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [ ]:
book_stats = ratings.groupby("ISBN")["Book-Rating"].agg(
    size="size",
    mean="mean"
).reset_index()
book_stats


top_books_with_info = books.merge(
    book_stats,
    on="ISBN",
    how="left"
)



top_books_with_info[["size", "mean"]].isna().sum()
print(top_books_with_info[["size", "mean"]].isna().sum())
print(top_books_with_info[["size", "mean"]].shape)
# There are 1203 out of 271360 books that have no ratings. 

top_books_with_info = top_books_with_info.fillna({"size": 0, "mean": 0})
print(top_books_with_info[["size", "mean"]].isna().sum())
print(top_books_with_info[["size", "mean"]].shape)

size    1203
mean    1203
dtype: int64
(270491, 2)
size    0
mean    0
dtype: int64
(270491, 2)

In [4]:
# -------- checking if can add one hot encoding to the categorical columns --------
object_cols = [col for col in user.columns if user[col].dtype == "object"]
print(object_cols)
object_nunique = list(map(lambda col: user[col].nunique(), object_cols))
d = dict(zip(object_cols, object_nunique))

# Print number of unique entries by column, in ascending order
print(sorted(d.items(), key=lambda x: x[1]))
# -------- can't --------

['Location']
[('Location', 56882)]

In [24]:
top_books_with_info["Book-Author"] = top_books_with_info["Book-Author"].str.capitalize()
top_books_with_info["Book-Title"] = top_books_with_info["Book-Title"].str.capitalize()
top_books_with_info["Publisher"] = top_books_with_info["Publisher"].str.capitalize()
top_books_with_info["Book-Author"] = top_books_with_info["Book-Author"].fillna("Unknown")
top_books_with_info["Author-Count"] = top_books_with_info.groupby("Book-Author")["ISBN"].transform("count")
top_books_with_info[["Book-Author", "Author-Count", "Book-Title"]].sort_values("Author-Count", ascending=False).head(10)

            Book-Author  Author-Count                          Book-Title
167995  Agatha christie           635                       Le train bleu
5259    Agatha christie           635         The murder of roger ackroyd
175867  Agatha christie           635  Jeux de glaces (le livre de poche)
215395  Agatha christie           635                  Ordeal by inocence
75983   Agatha christie           635                Hickory dickory dock
75981   Agatha christie           635                  Evil under the sun
75980   Agatha christie           635               Murder in mesopotamia
75979   Agatha christie           635             The murder at hazelmoor
223764  Agatha christie           635                 Mrs. mcginty's dead
110219  Agatha christie           635              The secret of chimneys

In [25]:
top_books_with_info["Publication_Count"] = top_books_with_info.groupby("Publisher")["ISBN"].transform("count")
top_books_with_info[["Publisher", "Publication_Count", "Book-Title"]].sort_values("Publication_Count", ascending=False).head(10)

,Publisher,Publication_Count,Book-Title
137339,Harlequin,7532.0,Lover's leap (heartbeat) (harlequin american r...
210780,Harlequin,7532.0,Whole truth (harlequin superromance 280)
210778,Harlequin,7532.0,"Day before dawn (harlequin superromance, no 295)"
186734,Harlequin,7532.0,In their footsteps (harlequin single title)
148569,Harlequin,7532.0,No strings heartbeat (reader's choice)
125632,Harlequin,7532.0,The sex diet (blaze)
49926,Harlequin,7532.0,Long tall texans iii (by request) (by request...
226030,Harlequin,7532.0,One night of love (top author) (harlequin pres...
216194,Harlequin,7532.0,Legacy
168437,Harlequin,7532.0,Too young to love

In [26]:
top_books_with_info["Author-Avg-Rating"] = top_books_with_info.groupby("Book-Author")["mean"].transform("mean") 
top_books_with_info["Author-Reader-Count"] = top_books_with_info.groupby("Book-Author")["size"].transform("sum")
top_books_with_info["Author-Popularity"] = top_books_with_info["Author-Avg-Rating"] * (top_books_with_info["Author-Reader-Count"] / 1000)
top_books_with_info[["Book-Author", "Author-Avg-Rating", "Author-Reader-Count", "Author-Popularity", "Book-Title"]].sort_values("Author-Popularity", ascending=False).drop_duplicates("Book-Author").head(10)

,Book-Author,Author-Avg-Rating,Author-Reader-Count,Author-Popularity,Book-Title
7841,Stephen king,3.903150,10178.0,39.726256,Dolores claiborne
40444,John grisham,3.813768,8818.0,33.629806,Rey de los pleitos
192204,Nora roberts,2.897050,8590.0,24.885660,Remember when
6031,James patterson,2.887803,5845.0,16.879208,The lake house
3908,J. k. rowling,5.561769,2908.0,16.173624,Quidditch through the ages
25825,Mary higgins clark,3.032529,4908.0,14.883652,"Weep no more, my lady"
2444,Michael crichton,3.311353,4277.0,14.162658,Airframe
189884,Dean r. koontz,3.045478,4313.0,13.135145,The eyes of darkness
9970,Janet evanovich,3.909480,3351.0,13.100667,Visions of sugar plums
26098,Anne rice,3.254278,3922.0,12.763279,Violin

In [11]:
features = [
    "Author-Count",
    "Year-Of-Publication",
    "Publication_Count",
    "size",
    "mean"
]
X = top_books_with_info[features]

In [ ]:

from sklearn.model_selection import train_test_split


X_train, y_train, X_test, y_test = train_test_split(X, top_books_with_info[features], test_size=0.2, random_state=42)

KeyError: 'Book-Rating'

In [ ]:
# y is the user ratings for the books, which is the target variable we want to predict.